Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "django-instance"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "django-instance"
  config.vm.provision "file", source: "emptyfile.txt", destination: "emptyfile.txt"

  config.vm.provision "shell", path: "install.sh"
end
